.Dd $Mdocdate$
.Dt FAQ isotop
.OS
.Sh NAME
.Nm isotop
.Nd une OpenBSD préconfigurée, simple (et amusante ?)

.Sh DESCRIPTION
.Nm 
est un script permettant de configurer OpenBSD pour obtenir un environnement de
travail agréable et pratique.
Les outils présents de base dans OpenBSD sont
privilégiés. Par conséquent, certains choix ont été faits pour se
concentrer sur un système simple et efficace.

.Sh FAQ

.Ss Où est mon bureau ?
Juste sous vos yeux.
Le gestionnaire de fenêtres par défaut dans isotop est 
.Xr cwm 5
Sa simplicité permet de mieux se concentrer et à être plus efficace.

Avant d'installer un autre gestionnaire de fenêtres ou environnement de
bureau, essayez cwm. Nous avons essayé de le rendre plus simple à
utiliser qu'il ne l'est déjà, et cela demandera peut-être un temps
d'adaptation.
(voir 
.Sx Comment utiliser mon bureau ?
).

.Ss Comment configurer une connexion WiFi ?
Lisez le man
.Xr hostname.if 5
et la documentation d'OpenBSD traduite
.Lk https://wiki.obsd4a.net/openbsd.org:faq:faq6#reseau-sans-fil réseau sans fil
Un outil pour faciliter les connexions sera publié dans la prochaine
version d'isotop, lorsque j'aurai une carte sans-fil.

.Ss Comment ajouter/supprimer des programmes
Un raccourci vers 
.Em pkg_mgr 
est présent dans le menu de cwm.

Sinon, lisez
.Lk https://wiki.obsd4a.net/openbsd.org:faq:faq15 gestion des paquets.

.Ss Pourquoi mon écran semble rouge ?
Puisqu'on pense à vos yeux, on lance automatiquement en début de session
.Xr sct 1
Vous pouvez utiliser dsch pour modifier la couleur, ou carrément retirer
sct du fichier 
.Pa $HOME/.xsession

.Ss Quel démon de notification puis-je utiliser ?
Vous pouvez installer
.Em dunst
et le lancer à chaque début de session en ajoutant dans
.Pa $HOME/.xsession
.Dl dunst &

.Ss Pourquoi cmus est le lecteur de musique par défaut ?
Il est léger et ne nécessite pas de lourdes dépendances..It est
modifiable et scriptable, et peut même se contrôler avec la souris si
vous n'aimez pas le clavier.

Vous pouvez bien entendu installer n'importe quel autre lecteur qui vous
plait davantage.

.Ss Comment quitter cmus sans le fermer ?
Si vous démarrez cmus avec le menu de cwm disponible par clic-droit sur
le bureau, il est lancé dans 
.Xr tmux 1
Il peut ainsi être détaché ou ouvert dans plusiers terminaux, mais
surtout peut continuer de jouer la musique lorsque la fenêtre est
fermée.
Pour détacher cmus, appuyez sur "ctrl-b" puis "d".

.Ss Quelles sont les différences avec une installation OpenBSD de base?
.Bl -bullet
.It
.Xr unwind 8
est configuré en tant que résolveur de nom de domaine par défaut.
.It
Un script appelé unwind-block est utilisé pour bloquer certains domaines. Il met à jour
la liste des "mauvais domaines" chaque semaine et est appelée avec
.Pa /etc/rc.local

Voir
.Sx Que fait unwind-block?
.It
Message personnalisé dans
.Pa /etc/boot.conf
.It
.Xr hotplugd 8
est configuré pour monter automatiquement votre clé USB dans 
.Pa /vol

Un lien est disponible
dans votre répertoire $HOME.
.It
Services activés: hotplugd, cups, xenodm, unwind.
.It
Désactivation de ulpt pour les imprimantes USB. Cela se passe dans 
.Pa /etc/rc.shutdown 
pour profiter de
KARL au redémarrage.

Voir
.Lk https://marc.info/?l=openbsd-misc&m=155746672110488&w=2 ce fil
.It
La configuration ntpd n'utilise pas google comme contrainte.
.It
L’apparence de Xenodm est personnalisée et configurable avec un script appelé
xenodm-config.
.It
Des paquets supplémentaires sont installés.

Voir
.Pa /usr/local/share/isotop/data/packages
.It
doas est configuré pour éviter la saisie d'un mot de passe pour certaines commandes. 

Voir
.Pa /etc/doas.conf
.It
.Xr cwm 5
est le gestionnaire de fenêtres par défaut. Il est pré-configuré et
livré
avec divers scripts pour faciliter la gestion des fenêtres pour les
utilisateurs n'aimant pas les claviers.
.It
iridium est le navigateur par défaut. Sont désactivées chaque option liée à
google et le tracking. Il est "unveiled" par défaut:
cela signifie que le navigateur ne peut lire des fichiers sur votre
ordinateur sauf dans
.Pa $HOME/Downloads

Il garde vos clés SSH et mots de passe inaccessibles par un éventuel
pirate.
Firefox fait aussi des appels à google et n'est pas "unveiled" pour le moment
(voir
.Lk https://marc.info/?l=openbsd-misc&m=152872551609819&w=2 ce fil
)
.It
Alt-L est mappé vers Esc pour les utilisateurs de vi :)
.It
Les traductions sont incluses: anglais et français pour l'instant.
.It
Quelques scripts et outils sont inclus dans
.Pa /usr/local/share/isotop/bin
et disponible dans votre
.Ev PATH
.No .

Voir
.Sx Quels scripts sont livrés?
.It
.Pa $HOME/.aliases
et
.Pa $HOME/.functions
sont remplis de choses (utiles?).
.It
$HOME/.kshrc contient de l'auto-complétion pour OpenBSD.
.It
Un fond d'écran aléatoire est défini à chaque session avec
GraphicsMagick.
.It
Le navigateur de fichiers est pcmanfm. Il est configuré pour avoir des
actions personnalisées via clic-droit (éditer une image, téléverser un fichier ...).
.El

.Ss Pourquoi ce nom?

Au début, isotop était image iso contenant tous les paquetages et
configuration pour l'installation.
Maintenant, c'est juste un script pour configurer OpenBSD.

Comme un isotope c'est une
variante d'OpenBSD avec quelques éléments supplémentaires, mais toujours OpenBSD.

.Ss Puis-je installer un autre navigateur Web?

Bien sûr.
Firefox et chrome, entre autres, sont disponibles dans les ports.
Cependant, nous avons choisi iridium car il est "unveiled", c’est-à-dire
qu’il ne peut pas accéder à vos fichiers personnels
contenant des mots de passe ou des clés SSH et il est plus respectueux de la vie privée que le chrome.

.Ss Puis-je installer un autre environnement de bureau?
Bien sûr.

Gnome, kde, lxde, xfce et d'autres sont disponibles pour OpenBSD via les ports.

.Ss Que fait unwind-block?

Pour économiser votre bande passante et filtrer les annonces sans 
addon dans le navigateur, un script appelé unwind-block est exécuté au démarrage (voir
.Pa /etc/rc.local
)

Tous les 7 jours, le script télécharge une liste des domaines
malveillants et les enregistre
dans
.Pa /var/unwind.block
Ainsi, unwind peut choisir de ne pas résoudre
leur noms.
Si vous essayez d’accéder à l’un de ces domaines (pourquoi?), Vous
obtiendrez un
message:

.Dq Le site web n'est pas disponible

.Ss Quels processus sont démarrés lorsque j'ouvre une session?

Consultez le fichier
.Pa $HOME/.xsession

.Ss Où sont stockés les fichiers d'isotop?

.Pa /usr/local/share/isotop

.Ss Quels scripts sont inclus?

.Bl -bullet
.It
dalarm: spécifiez une alerte, puis un nombre de minutes. Une notification 
affichera l'alerte après le délai.
.It
dcmus: choisissez un fichier à lire dans la liste de lecture de cmus
.It
dfm: un lanceur de fichiers utilisant dmenu.
.It
dgroupwin: sélectionne une fenêtre et assigne un groupe
.It
dman: lire une page de manuel
.It
dmenu_run_i: un dmenu_run amélioré pour pouvoir lancer une commande. Terminez avec un "!"
et la commande est ouverte dans un terminal. Exemple :
.Cm top!
.It
dsch: recherche sur le web.
Le moteur de recherche par défaut est duckduckgo si vous ne spécifiez pas de recherche
moteur.

Exemples :

.D1 moteur par défaut: OpenBSD, cryptage complet du disque
.D1 recherche sur openbsd misc list: obsdmisc firefox crash


.It
dsct : configurer la couleur de l'écran
.It
dyt: télécharger une vidéo avec
.Xr youtube-dl 1

L'URL sélectionnée est collée par défaut.
.It
gdoas: ouvre xterm pour taper le mot de passe doas utilisé pour d’autres scripts tels que
xenodm-config.
.It
imgmod: modifier une image en utilisant
.Xr gm 1

Les modifications supportées sont.
.Bl -bullet
.It
convertir en jpg
.It
convertir en png
.It
convertir en gif
.It
redimensionner
.It
tourner à gauche ou à droite
.El
.It
imgopti: optimise une image pour réduire son poids.
.It
networkcheck: vérifie l'accès à Internet
.It
openbsdupgrade: mise à niveau vers les dernières modifications de -stable avec
.Xr syspatch 8
.Xr fw_update 1
et
.Lk https://www.mtier.org/solutions/apps/openup/ openup
.It
pixcol: affiche le code html de la couleur du pixer situé sous le
pointeur.
.It
pixup: téléverse une image sur pix.toile-libre.org
.It
rdmwall: définit un fond d'écran aléatoire. Les fonds sont recherchés dans:
.Pa $HOME/Images/Wallpapers
;
.Pa /usr/local/share/isotop/walls
;
.Pa /usr/local/share/openbsd-backgrounds/landscape 
images du paquet
.Em openbsd-backgrounds
.It
scrot: prend une capture d'écran, enregistrée dans $HOME
.It
scrotup: fait une capture d'écran avec scrot et téléverse avec pixup
.It
send_dmesg.sh: envoyez votre dmesg aux développeurs OpenBSD pour aider
au support matériel.
.It
setwall: définit le fond d'écran.
.It
Web: un wrapper pour démarrer un navigateur web.
.It
xenodm-config: éditez la configuration et l'apparence de xenodm.
.El

.Ss Quelles actions personnalisée y a-t-il dans pcmanfm ?

.Bl -bullet
.It 
Modification d'images (tourner, redimensionner...)
.It
Optimisation d'image
.It
Upload d'image
.It
Définir l'image comme fond d'écran
.It
Jouer la musique dans cmus
.It
Imprimer avec l'imprimante par défaut (image, texte, pdf)
.El

.Sh Comment utiliser mon bureau?
.Ss Ouvrir une application
Au début, le bureau est vide.

Cliquez avec le bouton droit sur l'arrière-plan pour afficher le menu
d'applications et choisissez par
exemple, xterm. 

Vous pouvez également appuyer sur Alt-p pour afficher
.Mm dmenu
et écrire
.Dq xterm
puis appuyer sur Entrée.

Enfin, vous pouvez déplacer le pointeur vers le coin inférieur gauche pour afficher une fenêtre jgmenu.

.Ss Gestion basique des fenêtres

Vous pouvez faire glisser la fenêtre en appuyant sur Alt et en
maintenant le bouton gauche de la souris appuyé sur la fenêtre.

Pour redimensionner la fenêtre, appuyez sur Alt et faites un clic droit.

Vous n'avez probablement pas besoin de déplacer et de redimensionner les
fenêtres mais de les maximiser 
à la place, ou les cacher. Tout cela peut être fait avec des raccourcis clavier grâce à
.Xr cwm 1
mais vous ne vous en souviendrez peut-être pas tout le temps. Cliquez avec le bouton droit sur le bureau ou sur une bordure de fenêtre pour
voir les raccourcis:

.Bl -bullet
.It
Minimiser
.It
Maximiser
.It
Fermer
.It
Bureau : afficher le bureau
.It
Groupe : gestion des groupes
.El

Ensuite, cliquez sur la fenêtre cible.

.Ss Raccourcis clavier

Les Raccourcis clavier sont ceux de
.Xr cwm 1
par défaut.

Quelques autres sont ajoutés:
.Bl -bullet
.It
Alt-F4: fermer la fenêtre
.It
Alt-Shift-h/j/k/l: déplace la fenêtre à gauche/en bas/en haut/à droite de 
écran.
.It
Alt-s: démarrer le script
.Cm dsch
.It
Alt-x: démarre le script
.Cm dfm
.It
Alt-t et Alt-Shift-t: fenêtres en mosaïque (tiling)
.It
Alt-p: menu affiché pour démarrer une application
.It
Alt-f: menu des fenêtres
.It
Alt-g: associer un nouveau groupe à une fenêtre focalisée
.El

Voir
.Xr cwmrc 5
à personnaliser selon vos besoins.

.Ss Raccourcis souris 

Vous pouvez afficher les menus en cliquant sur le bureau ou sur la
.Em
bordure
.Non
d'une
fenêtre (assez grande par défaut).

.Bl -bullet
.It
Clic droit: menu application. vous pouvez lancer une application.
.It
Clic central: menu du groupe: affiche le groupe actif sur lequel basculer la visibilité
.It
Clic gauche: menu des fenêtres, pour focaliser une fenêtre.
.It
Faites défiler sur l'arrière-plan pour modifier le volume.
.It
Alt + clic droit: redimensionner la fenêtre
.It
Alt + clic gauche: déplacer la fenêtre
.El


.Ss À propos du menu fenêtres

Le menu fenêtres ressemble à ceci:
.Bd -literal
(4) ! [] Nom de la fenêtre
(4)   [] autre nom de fenêtre
(2) & [] un autre nom de fenêtre
(1) & [foo] encore un nom de fenêtre
.Ed

Entre parenthèses, vous voyez le groupe affecté à la fenêtre.

.D1 ! signifie que la fenêtre est focalisée.
.D1 & signifie que la fenêtre est masquée.
.D1 [foo]: la fenêtre a reçu l’étiquette "foo" avec le raccourci Ctrl-alt-n

.Ss À propos des espaces de travail

Il n'y a pas d'espaces de travail. Ils sont juste un moyen d'augmenter la taille de
l'écran, et si vous avez besoin d’un écran plus grand, le gestionnaire de fenêtres est probablement
dans l'erreur quelque part.
.Xr cwm 1
utilise à la place
le concept de 
.Em groupes.
Vous pouvez choisir d’afficher une ou plusieurs fenêtres groupées en fonction de votre
besoin.

Vous pouvez attribuer automatiquement un groupe à une fenêtre dans
.Pa $HOME/.cwmrc
ou vous pouvez utiliser 
.Cm dgroupwin
pour assigner un groupe à une fenêtre.

À tout moment, un clic du milieu sur le bureau affichera le "menu
groupe" pour
alterner la visibilité des groupes actifs.

.Sh À propos de dmenu
Les outils inclus utilisent dmenu.

C'est un menu affiché en haut de votre écran.
Écrivez ce dont vous avez besoin, ou une partie seulement, puis appuyez
sur Entrée pour sélectionner.

.D1 Retour: sélectionner
.D1 Esc: quitter le menu.
.D1 ctrl-y: coller la sélection

Voir
.Lk https://tools.suckless.org/dmenu/ site web de dmenu



.Sh BUGS
Bien sûr.

Veuillez les signaler à
.An prx
.Mt prx@ybad.name

.Sh SEE ALSO

.Xr cwm 1
.Xr cwmrc 5
.Xr dmenu 1
.Xr tmux 1
