.Dd $Mdocdate$
.Dt FAQ isotop
.OS
.Sh NAME
.Nm isotop
.Nd une OpenBSD préconfigurée, simple (et amusante ?)

.Sh DESCRIPTION
.Nm 
est un script permettant de configurer OpenBSD pour obtenir un environnement de
travail rapide, agréable et pratique.
Les outils présents de base dans OpenBSD sont
privilégiés. Par conséquent, certains choix ont été faits pour se
concentrer sur un système simple et efficace.

.Sh FAQ

.Ss Comment me servir de ce bureau ?
Le gestionnaire de fenêtres par défaut dans isotop est 
.Lk http://dwm.suckless.org/ dwm
avec quelques modifications.
Sa simplicité permet de mieux se concentrer et à être plus efficace.

Avant d'installer un autre gestionnaire de fenêtres ou environnement de
bureau, essayez dwm. Nous avons essayé de le rendre plus simple à
utiliser qu'il ne l'est déjà, et cela demandera peut-être un temps
d'adaptation.

Pour commencer : 

En haut à gauche, vous voyez les numéros des espaces de
travail suivi d'un symbole. Vous pouvez cliquer dessus pour en changer.

En haut à droit, une barre de status indique l'heure, la date, le
volume sonore, la charge de la batterie et la chanson jouée.

Quelques raccourcis : 

.Bl -bullet
.It clic gauche sur la barre de status ou le fond d'écran : affiche le menu pour
ouvrir une application
.It clic droit sur la barre de status ou le fond d'écran : affiche le menu de session
.It clic gauche ou scroll sur le titre d'une fenêtre : affiche la
fenêtre suivante.
.It clic droit sur le titre d'une fenêtre : ferme la
fenêtre.
.It ctrl-shift-Enter : ouvre un terminal
.It alt-p: affiche dmenu pour ouvrir une application
.El

Bien sûr, ce n'est qu'un mince aperçu.

Voir 
.Xr dwm-isotop 1
pour plus d'informations sur les possibilités de la session
isotop.

.Ss Comment installer isotop pour un autre utilisateur ?
Facile, il suffit de lancer le script d'installation avec cet
utilisateur. Seule la configuration utilisateur sera copiée si la
dernière version d'isotop est installée.

.Ss Comment recompiler moi-même dwm, dmenu, slstatus, lsdesktop ?
Ces outils sont disponibles dans le dossier
.Pa isotop-files/src
dispnibles après installation dans votre dossier personnel. Ils
sont toujours là si vous ne les avez pas supprimés. Sinon,
voir ici :

.Lk https://framagit.org/3hg/isotop/-/tree/master/isotop-files/src

.Ss Comment configurer une connexion WiFi ?
Lisez le man
.Xr hostname.if 5
et la documentation d'OpenBSD traduite
.Lk https://wiki.obsd4a.net/openbsd.org:faq:faq6#reseau-sans-fil réseau sans fil
Un outil pour faciliter les connexions sera publié dans une prochaine
version d'isotop, lorsque le développeur aura une carte sans-fil.

.Ss Comment ajouter/supprimer des programmes
Ouvrez
.Xr pkg_mgr 1
dans un terminal.

Sinon, lisez
.Lk https://wiki.obsd4a.net/openbsd.org:faq:faq15 gestion des paquets.

.Ss Pourquoi mon écran semble rouge ?
Puisqu'on pense à vos yeux, on lance automatiquement en début de session
.Xr sct 1
Vous pouvez utiliser 
.Xr dsct 1
pour modifier la couleur, ou carrément retirer
.Cm sctd 1>/dev/null &
du fichier 
.Pa $HOME/.start
.

.Ss Pourquoi mpd est le lecteur de musique par défaut ?
Il est léger et ne nécessite pas de lourdes dépendances.
Par ailleurs, c'est très simple de le contrôler
grâce à divers scripts.
L'outil 
.Cm ncmpc
est installé pour vous donner une interface à mpd.
Par défaut, toute la musique placée dans le dossier
.Pa $HOME/Musique
sera disponible à la lecture.

À ce propos, voir : 

.Bl -bullet
.It
.Xr dmpc 1
.It
.Xr mpc 1
.It
.Xr ncmpc 1
.El


.Ss Quelles sont les différences avec une installation OpenBSD de base?
.Bl -bullet
.It
.Xr unwind 8
est configuré en tant que résolveur de nom de domaine local
par défaut. Ainsi, vous ne dépendez pas d'un fournisseur
d'accès à internet pour réaliser cette tâche
(anti-censure).
.Pp
Un fichier
.Pa /var/unwind.block
contient une liste de domaines connus comme malveillants ou
publicitaires. Cette liste est mise à jour
une fois par semaine au démarrage via le script
.Pa /etc/rc.local.

.Pp
Cette liste est récupérée depuis le site
.Lk https://ybad.name/evils.html de l'auteur d'isotop.

Si vous essayez d’accéder à l’un de ces domaines (pourquoi?), Vous
obtiendrez un
message:

.Dq Le site web n'est pas disponible

.It
.Xr hotplugd 8
est configuré pour monter automatiquement votre clé USB dans 
.Pa /vol

Un lien est disponible
dans votre répertoire $HOME/Médias.
.It
Services activés: hotplugd, cups, xenodm, unwind.
.It
Désactivation de ulpt pour les imprimantes USB. Cela se passe dans 
.Pa /etc/rc.shutdown 
pour profiter de
KARL au redémarrage.

Voir
.Lk https://marc.info/?l=openbsd-misc&m=155746672110488&w=2 ce fil
.It
La configuration ntpd n'utilise pas google comme contrainte.
.It
L’apparence de Xenodm est personnalisée, traduite et configurable avec un script appelé
xenodm-config.
.It
Des paquets supplémentaires sont installés.

Voir
.Lk https://framagit.org/3hg/isotop/-/blob/master/isotop-files/packages.txt
.It
doas est configuré pour éviter la saisie d'un mot de passe pour certaines commandes. 

Voir
.Pa /etc/doas.conf
.It
.It
.Xr firefox 1
est le navigateur par défaut.
Il est "unveiled" par défaut:
cela signifie que le navigateur ne peut lire des fichiers sur votre
ordinateur sauf dans
.Pa $HOME/Downloads
et
.Pa /tmp
pour plus de sécurité.

Il garde vos clés SSH et mots de passe inaccessibles par un éventuel
pirate.
.It
Alt-L est mappé vers Esc pour les utilisateurs de vi :)
.It
Les traductions sont incluses: anglais et français pour l'instant.
.It
Quelques scripts et outils sont inclus dans votre dossier personnel
.Pa /$HOME/bin
et disponible dans votre
.Ev PATH
.No .
Ainsi, vous pouvez facilement les modifier ou les supprimer s'ils ne
vous plaisent pas.

Voir
.Sx Quels scripts sont livrés?
.It
.Pa $HOME/.aliases
et
.Pa $HOME/.functions
sont remplis de choses (utiles?).
.It
$HOME/.kshrc contient de l'auto-complétion pour OpenBSD.
.It
Si un fichier 
.Pa $HOME/.wallpaper
est trouvé, alors il est définit comme fond
d'écran.
Copiez le fond d'écran de votre choix à sa place.
.It
Le navigateur de fichiers est 
.Lk http://roland65.free.fr/xfe/ xfe
.Pp
Il est à la fois léger et suffisamment configurable pour
permettre l'accès à des actions personnalisées via
clic-droit.
.It
Le pointeur de la souris est caché grâce à 
.Xr xbanish 1
.It
Le thème de couleur "nord" est installé pour les applications X. Voir.
.Lk  https://www.nordtheme.com/
.El

.Ss Pourquoi ce nom?

Au début, isotop était image iso contenant tous les paquetages et
configuration pour l'installation.
Maintenant, c'est juste un script pour configurer OpenBSD.

Comme un isotope c'est une
variante d'OpenBSD avec quelques éléments supplémentaires, mais toujours OpenBSD.

.Ss Why c'est sombre ?
Parce que le développeur aime bien, et ça économise l'énergie de ne pas
allumer les pixels.

.Ss Puis-je installer un autre environnement de bureau?
Bien sûr.

Gnome, kde, lxde, xfce et d'autres sont disponibles pour OpenBSD via les ports.

.Ss Quels processus sont démarrés lorsque j'ouvre une session?

Consultez le fichier
.Pa $HOME/.start

.Ss Quels scripts sont inclus?

.Bl -bullet
.It
bdmenu: permet de lancer une commande via dmenu avec historique et
possibilité d'exécuter une commande dans un terminal en
terminant l'entrée par 
.Dq !
.It
checkbatt : ce script est lancé périodiquement via 
.Xr crontab 5
et permet d'afficher une alerte si la batterie devient faible.
.It
dalarm: spécifiez une alerte, puis un nombre de minutes. Une notification 
affichera l'alerte après le délai.
.It 
ddesktop : affiche dans un dmenu une liste des applications disponibles
sur le système après avoir listé les fichiers
.desktop présents.
Exemple:
.Cm top!
.Pp
Ce menu est disponible en faisant un clic-gauche sur la barre de status
ou le fond d'écran.
.It
dfm: un lanceur de fichiers utilisant dmenu.
.It
dloadbmk: ouvre une page web listée dans
.Pa $HOME/.bookmarks
.It
dman : permet d'ouvrir rapidement une page man (merci eol)
.It
dmpc: choix d'une chanson à jouer dans mpd
.It
dsch: recherche sur le web.
Le moteur de recherche par défaut est duckduckgo si vous ne spécifiez pas de recherche
moteur.

Exemples :

.D1 moteur par défaut: OpenBSD, cryptage complet du disque
.D1 recherche sur openbsd misc list: obsdmisc firefox crash

.It
dsct : configurer la couleur de l'écran
.It
dshot : capture d'écran avec possibilité d'upload et copie
dans le presse papier
.It
dsshmenu : ouvre une session ssh.
.It
dyt: télécharger une vidéo avec
.Xr youtube-dl 1

L'URL sélectionnée est collée par défaut.
.It
gdoas: ouvre xterm pour taper le mot de passe doas utilisé pour d’autres scripts
.It
imgmod: modifier une image en utilisant
.Xr gm 1

Les modifications supportées sont.
.Bl -bullet
.It
convertir en jpg
.It
convertir en png
.It
convertir en gif
.It
redimensionner
.It
tourner à gauche ou à droite
.El
.It
imgopti: optimise une image pour réduire son poids.
.It
networkcheck: vérifie l'accès à Internet
.It
openbsdupgrade: mise à niveau vers les dernières modifications de -stable avec
.Xr syspatch 8
.Xr fw_update 1
.Xr pkg_add 1
.It
pixcol: affiche le code html de la couleur du pixer situé sous le
pointeur.
.It
pixup: téléverse une image sur pix.toile-libre.org
.It
scrot : réalise une capture d'écran.
.It
send_dmesg.sh: envoyez votre dmesg aux développeurs OpenBSD pour aider
au support matériel.
.It
sessionmenuisotop: Ouvre une fenêtre pour éteindre/redémarrer/quitter
la session...
.Pp
Ce menu est disponible en faisant un clic-droit sur la barre de status
ou le fond d'écran.
.It
setwall: définit le fond d'écran.
.It
term: ouvre un terminal. PAr défaut, xterm est utilisé.
.El

.Sh À propos de dmenu
Les outils inclus utilisent dmenu patché pour pouvoir aussi
l'utiliser avec la souris.

C'est un menu affiché en haut de votre écran.
Écrivez ce dont vous avez besoin, ou une partie seulement, puis appuyez
sur Entrée pour sélectionner ou bien cliquez dessus
la lignee désirée. Un clic droit ou bien la touche echap
ferment le menu.

.D1 Retour ou clic gauche: sélectionner
.D1 Esc ou clic droit: quitter le menu.
.D1 ctrl-y: coller la sélection

Voir
.Lk https://tools.suckless.org/dmenu/ site web de dmenu

.Sh BUGS
Bien sûr.

Veuillez les signaler à
.An prx
.Mt prx@ybad.name

.Sh SEE ALSO

.Xr bdmenu 1
.Xr daddbmk 1
.Xr dalarm 1
.Xr dfm 1
.Xr ddesktop 1
.Xr dwm-isotop 1
.Xr dmenu 1
.Xr dmpc 1
.Xr firefox 1
.Xr mpc 1
.Xr ncmpc 1
.Xr pkg_mgr 1
.Xr tmux 1
.Xr slstatus 1
