.Dd $Mdocdate$
.Dt bdmenu 1
.Os
.Sh NAME
.Nm bdmenu
.Nd an application launcher like 
.Xr dmenu_run 1
with recent and in-term capability
.Sh DESCRIPTION
The
.Nm
utility show a list of availables executables starting with most
recently executed.

If the input ends with 
"!"
then the command is executed in a terminal.
.Sh SEE ALSO
.Xr dmenu 1
.Xr term 1
.Sh EXAMPLES
.Bd -literal
	top! : display top in a terminal
	firefox : open firefox
.Ed
.Sh AUTHORS
.An prx prx@ybad.name
