.Dd $Mdocdate$
.Dt dloadbmk 1
.Os
.Sh NAME
.Nm dloadbmk
.Nd load a bookmark from 
.Pa $HOME/.bookmarks
.Sh DESCRIPTION
.Nm
displays content of 
.Pa $HOME/.bookmarks
in 
.Xr dmenu 1
to load the desired url in the default browser
defined by the 
.Ev BROWSER 
variable.
.Sh SEE ALSO
.Xr daddbmk 1
.Xr dmenu 1
.Xr term 1
.Sh AUTHORS
.An prx prx@ybad.name
