.Dd $Mdocdate$
.Dt dlocate 1
.Os
.Sh NAME
.Nm dlocate
.Nd search and open files
.Sh DESCRIPTION
.Nm
allows you to quickly search for a file in the user 
directory through a cache. 
The list is displayed in
.Xr dmenu 1
and the selection is open with
.Xr xdg-open 1
.Sh SEE ALSO
.Xr daddbmk 1
.Xr dmenu 1
.Xr locate 1
.Xr locate.updatedb 8
.Xr xdg-open 1
.Sh AUTHORS
.An prx prx@ybad.name
