.Dd $Mdocdate$
.Dt dshot 1
.Os
.Sh NAME
.Nm dshot
.Nd 
allows a screenshot:
.Bl
.It
from the entire screen
.It
from a part of the screen
.It
from a part of the screen then copy it to clipboard
.It
from a part of the screen then upload it
.El
.Sh SEE ALSO
.Xr dmenu 1
.Xr xclip 1
.Xr pixup 1
.Sh AUTHORS
.An prx prx@ybad.name
