.Dd $Mdocdate$
.Dt dwm-isotop 1
.Os
.Sh NAME
.Nm dwm-isotop
.Nd custom dwm window manager
.Sh DESCRIPTION
Here is the list of changes that have been
made to the default configuration of
.Lk dwm https://dwm.suckless.org

The "Mod1" key corresponds to Alt.

.Ss Applied patchs

.Bl -bullet
.It
.Lk https://dwm.suckless.org/patches/bottomstack/ bottomstack
Add a new layout for vertical screens. Alt-v and Alt-Shift-v to select them.
.It
.Lk http://dwm.suckless.org/patches/gaplessgrid/ gaplessgrid
Grid layout accessible with Mod1-g
.It
.Lk http://dwm.suckless.org/patches/focusmaster/ focusmaster
used to select the master window by
a shortcut.
.It
.Lk http://dwm.suckless.org/patches/resetnmaster/ resetnmaster
to reset the number of windows in the
master area.
.It
.Lk https://dwm.suckless.org/patches/hide_vacant_tags/ hide_vacant_tags
.It
.Lk https://dwm.suckless.org/patches/tagintostack/ tagintostack
.It
.Lk https://dwm.suckless.org/patches/focusurgent/ focusurgent
.El

.Ss  Appearance
Colors comes from Nord theme
.Lk https://www.nordtheme.com/ nord

.Lk https://sourcefoundry.org/hack/ Hack
font is used.

.Ss  Mouse Bindings

On window titlebar:
.Bl -bullet
.It
Left clic or scroll: cycle through windows
.It
Right clic: close the window
.It
Middle clic: put window in master area
.El

On window itself:
.Bl -bullet
.It
Mod1-left-clic: déplace la fenêtre
.It
Mod1-middle-clic: active/désactive le mode flottant
.It
Mod1-right-clic: redimensionne la fenêtre
.It
Mod1-Shift-left-clic: put window in master area
.El

On statusbar:
.Bl
.It
left-clic: open the menu 
.Xr ddesktop 1
.It
right-clic: open session menu
.Xr dsession 1
.It
middle-clic: open a terminal
.It
scroll: manage sound volume
.El

.Ss  Key Bindings
Azerty keyboards can now be used with dwm without worries,
the equivalences between the numbers and the typography characters
are integrated. (& matches 1,
é to 2, " to 3 ...). The same goes for the multi-screen management: 
Mod1-. becomes Mod1-;.

The default dwm shortcuts are mostly kept. Here are some
some new: 

.Bl
.It
Mod1-p: open 
.Xr bdmenu1
.It
Mod1-u: add a window in the master area (replace
Mod1-i)
.It
Mod1-o: reset the window number to 1 in the master area.
.It
Mod1-z: zoom mode: maximized window
.It
Mod1-d: deck mode: side windows stacked
.It
Mod1-F4: close the window. Idem Mod1-Shift-c
.It
Mod1-F2: open bdmenu. Idem Mod1-p
.It
Mod1-=: increase sound level
.It
Mod1-): decrease sound level
.It
Mod1-s: open
.Xr dsch 1
.It
Mod1-w: open
.Xr dloadbmk 1
.It
Mod1-q: open
.Xr dmpc 1
.It
Mod1-Shift-Backspace: lock the session
.It
Impr Ecran: open
.Xr dshot 1
.It
Mod1-Backspace or Mod1-x: open the floating terminal
.Xr scratchterm 1
.It
Mod1-a : focus urgent window
.It
Mod1-v : layout bstack
.It
Mod1-Shift-v : layout bstackhoriz
.It
Mod1-g : grid layout
.El

Mpd Key Bindings: 
.Bl
.It
Mod1-Ctrl-h: mpc prev : previous song
.It
Mod1-Ctrl-j: mpc toggle : play/pause
.It
Mod1-Ctrl-k: mpc play : play playlist
.It
Mod1-Ctrl-l: mpc next : next song
.El

.Sh SEE ALSO
.Xr dwm 1
