.Dd $Mdocdate$
.Dt imgmod 1
.Os
.Sh NAME
.Nm imgmod
.Nd image modification
.Sh DESCRIPTION
.Nm 
proposes a list of modifications to be made on an image
passed as argument.

GaphicsMagick is used for modifications.

It is currently possible to:
.Bl -bullet
.It
Resize an image
.It
Convert in jpg, png or gif
.It
Turn clockwise
.It
Turn anti-clockwise
.El
.Sh SEE ALSO
.Xr dmenu 1
.Xr gm 1
.Sh AUTHORS
.An prx prx@si3t.ch
