.Dd $Mdocdate$
.Dt lsdesktop 1
.Os
.Sh NAME
.Nm lsdesktop
.Nd lists .desktop files
.Sh SYNOPSIS
.Op Fl h
.Op Fl s Ar separator
.Sh DESCRIPTIION
.Nm
lists the .desktop files present on the system.

It displays them this way:
.Bd -literal
	Category|Name|command
.Ed

If the environment variable
.Ev LANG
is defined, the translation of the application name is sought.

The locations where .desktop files are searched are:
.Bl -bullet
.It
.Pa $HOME/.local/share/applications/
.It
.Pa /usr/local/share/applications/
.It
.Pa /usr/share/applications/
.El

A file
.Pa $HOME/.config/lsdesktop.exclude
can contain a list of .desktop files that should not be put in the list
For example:
.Bd -literal 
	gtk3-demo.desktop
	gtk3-icon-browser.desktop
	gtk3-widget-factory.desktop
.Ed

.Sh EXAMPLE
.Cm lsdesktop -s '::' | column -t -s '::'

.Sh AUTHORS
.An prx prx@ybad.name
