.Dd $Mdocdate$
.Dt pixup 1
.Os
.Sh NAME
.Nm pixup
.Nd upload image
.Sh DESCRIPTION
.Nm
upload in line the picture passed as argument.

Picture is displayed in the default
.Ev BROWSER
to propose integration codes for the image.

Servers that could be used, in order:
.Bl
.It
.Lk https://pix.toile-libre.org
.It
.Lk https://transfer.sh
.It
.Lk https://0x0.st
.El

.Sh SEE ALSO
.Xr curl 1
.Sh AUTHORS
.An prx prx@ybad.name
