.Dd $Mdocdate$
.Dt send_dmesg 1
.Os
.Sh NAME
.Nm send_dmesg
.Nd send system informations to 
.Ox
devlopers
.Sh DESCRIPTIION
.Nm
retrieves information about your hardware.
You can decide to send them to
OpenBSD developers indicating what works and what doesn't.
.Sh SEE ALSO
.Xr dmesg 8
.Xr sysctl 8
.Xr mail 1
.Xr xmessage 1
.Sh AUTHORS
.An prx prx@si3t.ch
