.Dd $Mdocdate$
.Dt wobsd 1
.Os
.Sh NAME
.Nm wobsd
.Nd Add a WiFi access point
.Sh DESCRIPTIION
.Nm
detects accessible WiFi access points
to connect to it automatically afterwards.

It only allows access to WPA2 access points for
the moment.

If a wired interface is detected, then it is
defined as preferred access.
.Sh SEE ALSO
.Xr hostname.if 5
.Xr ifconfig 8
.Sh AUTHORS
.An prx prx@ybad.name
