.Dd $Mdocdate$
.Dt bdmenu 1
.Os
.Sh NAME
.Nm bdmenu
.Nd un lanceur d'applications comme 
.Xr dmenu_run 1
avec gestion des entrées
récentes et possiblité d'ouvrir dans un terminal.
.Sh DESCRIPTION
.Nm
montre une liste des commandes pouvant être exécutées avec, en
premier, les plus récemment ouvertes.

Si l'entrée choisie se termine par un "!", la commande est ouverte
dans un terminal.
.Sh VOIR AUSSI
.Xr dmenu 1
.Xr term 1
.Sh EXEMPLES
.Bd -literal
	top! : ouvre "top" dans un terminal
	firefox : ouvre firefox
.Ed
.Sh AUTHORS
.An prx prx@ybad.name
