.Dd $Mdocdate$
.Dt daddbmk 1
.Os
.Sh NAME
.Nm daddbmk
.Nd ajoute un marque page dans
.Pa $HOME/.bookmarks
.Sh DESCRIPTION
.Nm
affiche le lien sélectionné dans 
.Xr dmenu 1
rcupère le titre de la page avec
.Xr curl 1
et affiche ensuite dans l'éditeur par défaut le fichier
pour une éventuelle modification.

Chaque ligne correspond à une entrée du type : 
.Bd -literal
description https://url
.Ed

.Sh VOIR AUSSI
.Xr dloadbmk 1
.Xr dmenu 1
.Xr curl 1
.Xr term 1
.Sh AUTHORS
.An prx prx@ybad.name
