.Dd $Mdocdate$
.Dt ddesktop 1
.Os
.Sh NAME
.Nm ddesktop
.Nd Lanceur d'applications
.Sh DESCRIPTION
.Nm 
liste les applications à partir des fichiers .desktop
présents sur le système. Choisir une entrée permet
de lancer la commande listée.
.Sh VOIR AUSSI
.Xr lsdesktop 1
.Xr dmenu 1
.Sh AUTHORS
.An prx prx@ybad.name
