.Dd $Mdocdate$
.Dt dloadbmk 1
.Os
.Sh NAME
.Nm dloadbmk
.Nd charge un marque page à partir de 
.Pa $HOME/.bookmarks
.Sh DESCRIPTION
.Nm
affiche le contenu du fichier
.Pa $HOME/.bookmarks
dans
.Xr dmenu 1
pour charger l'url souhaités dans le navigateur par défaut
définit par la variable
.Ev BROWSER
.Sh VOIR AUSSI
.Xr daddbmk 1
.Xr dmenu 1
.Xr term 1
.Sh AUTHORS
.An prx prx@si3t.ch
