.Dd $Mdocdate$
.Dt dlocate 1
.Os
.Sh NAME
.Nm dlocate
.Nd chercher et ouvrir un fichier
.Sh DESCRIPTION
.Nm
permet de chercher un fichier rapidement dans le répertoire
utilisateur grâce à un cache.
La liste est affichée dans
.Xr dmenu 1
et la sélection est ouverte avec
.Xr xdg-open 1
.Sh VOIR AUSSI
.Xr daddbmk 1
.Xr dmenu 1
.Xr locate 1
.Xr locate.updatedb 8
.Xr xdg-open 1
.Sh AUTHORS
.An prx prx@ybad.name
