.Dd $Mdocdate$
.Dt dman 1
.Os
.Sh NAME
.Nm dman
.Nd chercher et lire une page man
.Sh DESCRIPTION
.Nm
liste toutes les pages man disponibles et permet de l'ouvrir dans un
terminal dédié.
.Sh VOIR AUSSI
.Xr dmenu 1
.Xr locate 1
.Xr locate.updatedb 8
.Sh AUTHORS
.An eol jul@ldd.fr
.An prx prx@ybad.name
