.Dd $Mdocdate$
.Dt dsch 1
.Os
.Sh NAME
.Nm dsch
.Nd effectue une recherche sur le web
.Sh DESCRIPTION
.Nm
Permet d'effectuer une recherche en ligne à partir d'un moteur au
choix.

Le navigateur définit par la variable
.Ev BROWSER
est utilisé pour ouvrir le lien.

.Sh VOIR AUSSI
.Xr dmenu 1
.Sh AUTHORS
.An prx prx@ybad.name
