.Dd $Mdocdate$
.Dt dshot 1
.Os
.Sh NAME
.Nm dshot
.Nd 
permet la capture :
.Bl
.It de l'écran entier
.It d'une partie de l'écran
.It d'une partie puis copie dans le presse-papier
.It D'une partie puis mise en ligne
.El
.Sh VOIR AUSSI
.Xr dmenu 1
.Xr xclip 1
.Xr pixup 1
.Sh AUTHORS
.An prx prx@ybad.name
