.Dd $Mdocdate$
.Dt dwm-isotop 1
.Os
.Sh NAME
.Nm dwm-isotop
.Nd gestionnaire de fenêtre dwm personnalisé
.Sh DESCRIPTION
Voici la liste des modifications qui ont été
apportés à la configuration par défaut de
.Lk dwm https://dwm.suckless.org

La touche "Mod" correspond à Alt.

.Ss Patches appliqués

.Bl
.It 
.Lk http://dwm.suckless.org/patches/attachbottom/ attachbottom
pour afficher les nouvelles fenêtres sur le côté
plutôt que dans la zone principale. Cela évite un vol de
focus inattendu
.It 
.Lk http://dwm.suckless.org/patches/focusmaster/ focusmaster
permet de sélectionner la fenêtre de la zone principal en
un raccourci.
.It 
.Lk http://dwm.suckless.org/patches/deck/ deckdouble
Ajoute un nouvel arrangement où les fenêtres mises de
côté sont empilées.
.It 
.Lk http://dwm.suckless.org/patches/resetnmaster/ resetnmaster
pour remettre à zéro l enombre de fenêtres dans la
zone principale.
.El

.Ss  Apparence
Les couleurs du thème
.Lk https://www.nordtheme.com/ nord
sont appliquées.

La police
.Lk https://sourcefoundry.org/hack/ Hack
est utilisée.

.Ss  Raccourcis souris

Sur la barre de titre des fenêtres:
.Bl
.It clic gauche ou scroll : change de fenêtre
.It clic droit : ferme la fenêtre
.It clic milieu : déplace la fenêtre dans la zone
principale
.El

Sur la fenêtre:
.Bl
.It Mod-clic gauche : déplace la fenêtre
.It Mod-clic milieu : active/désactive le mode flottant
.It Mod-clic droit : redimensionne la fenêtre
.It Mod-Shift-clic gauche : déplace la fenêtre dans la
zone principale
.El

Sur la barre de status:
.Bl
.It clic-gauche : ouvre le menu 
.Xr ddesktop 1
.It clic-droit : ouvre le menu de session
.Xr dsession 1
.It clic-milieu : ouvre un terminal
.It scroll : modifie le folume sonore
.El

.Ss  Raccourcis claviers
Les claviers de type azerty peuvent maintenant utiliser dwm sans soucis,
les équivalences entre les nombres et les caractères de
typographie sont intégrées. (& correspond à 1,
é au 2, " au 3...). Il en va de même pour la gestion
multi-écran (utilisation de "," et ";").

Les raccourcis par défaut de dwm sont pour la pluart conservés. En voici
quelques nouveaux : 

.Bl
.It Mod-p : ouvre 
.Xr bdmenu 1
.It Mod-u : ajoute une fenêtre dans la zone principale (remplace
Mod-d)
.It Mod-o : remet à 1 le nombre de fenêtres dans la zone
principale.
.It Mod-z : mode monocle (zoom) : fenêtres maximisées
.It Mod-d : mode deck : fenêtres mises de côté
empilées
.It Mod-F4 : ferme le fanêtre. Identique à Mod-Shift-c
.It Mod-F2 : Ouvre bdmenu. Identique à Mod-p
.It Mod-= : augmente le volume sonore
.It Mod-) : diminue le volume sonore
.It Mod-s : ouvre
.Xr dsch 1
.It Mod-w : ouvre
.Xr dloadbmk 1
.It Mod-q : ouvre
.Xr dmpc 1
.It Mod-Shift-Effacer (backspace) : verouille la session
.It Impr Ecran : ouvre
.Xr dshot 1
.It Mod-Backspace ou Mod-x : ouvre le terminal flottant
.Xr scratchterm 1
.El

Pour mpd : 
.Bl
.It Mod-Ctrl-h : mpc prev : chanson précédente
.It Mod-Ctrl-j : mpc toggle : joue/pause la lecture
.It Mod-Ctrl-k : mpc play : joue la playlist
.It Mod-Ctrl-l : mpc next : chanson suivante
.El

.Sh VOIR AUSSI
.Xr dwm 1
