.Dd $Mdocdate$
.Dt imgmod 1
.Os
.Sh NAME
.Nm imgmod
.Nd modification d'image
.Sh DESCRIPTION
.Nm 
propose une liste de modifications à effectuer sur une image
passée en argument.

GaphicsMagick est utilisé pour les modifications.

Il est actuellement possible de :
.Bl
.It Redimensionner une image
.It convertir en jpg, png ou gif
.It Tourner en sens horaire
.It Tourner en sens anti-horaire
.El
.Sh VOIR AUSSI
.Xr dmenu 1
.Xr gm 1
.Sh AUTHORS
.An prx prx@ybad.name
