.Dd $Mdocdate$
.Dt pixup 1
.Os
.Sh NAME
.Nm pixup
.Nd upload d'image
.Sh DESCRIPTION
.Nm
charge en ligne l'image passée en argument.

L'image est ensuite affichée dans le navigateur définit
par la variable  
.Ev BROWSER
pour proposer la
copie de codes d'intégration de l'image.

Les plateformes suivantes sont utilisées, dans l'ordre
.Bl -bullet
.It
.Lk https://pix.toile-libre.org
.It
.Lk https://transfer.sh
.It
.Lk https://0x0.st
.El

.Sh VOIR AUSSI
.Xr curl 1
.Sh AUTHORS
.An prx prx@ybad.name
