.Dd $Mdocdate$
.Dt send_dmesg 1
.Os
.Sh NAME
.Nm send_dmesg
.Nd envoi d'information aux développeurs d'
.Ox
.Sh DESCRIPTIION
.Nm
récupère des informations sur votre matériel.
Vous pouvez décider de les envoyer aux
développeurs d'OpenBSD en indiquant ce qui fonctionne ou non.
.Sh VOIR AUSSI
.Xr dmesg 8
.Xr sysctl 8
.Xr mail 1
.Xr xmessage 1
.Sh AUTHORS
.An prx prx@ybad.name
