.Dd $Mdocdate$
.Dt wobsd 1
.Os
.Sh NAME
.Nm wobsd
.Nd Ajout d'un point d'accès WiFi
.Sh DESCRIPTIION
.Nm
permet de détecter les points d'accès WiFi accessibles
pour s'y connecter automatiquement par la suite.

Il ne permet d'accéder qu'aux points d'accès WPA2 pour
l'instant.

Si une interface filaire est détectée, alors elle est
définie comme accès préféré.
.Sh VOIR AUSSI

.Xr hostname.if 5
.Xr ifconfig 8
