.\"	$OpenBSD$
.\"
.\" Written by thuban <thuban@yeuxdelibad.net>.
.\" Licence MIT
.\"
.TH zeniTK 1 "May 2017"
.SH NAME
zeniTK \- Simple dialogs for scripts
.SH SYNOPSIS
.B zeniTK

.SH DESCRIPTION
.PP
\fBzeniTK\fP display dialogs using Tk library and return user input.

.SH OPTIONS
Options are relative to window of specific to dialog.

.PP 
Available dialogs

.TP
.B \-\-entry
Display text entry dialog
.TP
.B \-\-error
Display error dialog
.TP
.B \-\-warning
Display warning dialog
.TP
.B \-\-info
Display info dialog
.TP
.B \-\-file\-selection
Display file selection dialog
.TP
.B \-\-color\-selection
Display color selection dialog
.TP
.B \-\-text\-info
Display editable text information dialog
.TP
.B \-\-progress
Display progress bar dialog
.TP
.B \-\-question
Display question dialog
Return 0 if answer is yes, 1 otherwise
.TP
.B \-\-list
Show a list of possibilities

.PP
General options

.TP
.B \-\-title
Set dialog title
.TP
.B \-\-window\-icon
Set dialog window icon
.TP
.B \-\-width
Set dialog width
.TP
.B \-\-height
Set dialog height
.TP
.B \-\-timeout
Set dialog timeout before closing it
.TP
.B \-\-font
Set dialog font
.TP
.B \-\-fontsize
Set dialog fontsize

.PP 
Entry dialog options

.TP
.B \-\-text
Set dialog text
.TP
.B \-\-entry\-text
Set dialog entry text

.PP 
File selection dialog options

.TP
.B \-\-multiple
Allow multiple selection
.TP
.B \-\-directory
Activate directory selection
.TP
.B \-\-separator
Specify separator used when returning multiple selections
.TP
.B \-\-file\-filter
Sets a filename filter
\-\-file\-filter="NAME | PATTERN" 

.PP
Color selection options

.TP
.B \-\-color
Set initial color

.PP
Text info dialog options

.TP
.B \-\-text
Set dialog text
.TP
.B \-\-entry\-text
Set dialog entry text


.PP
Progress dialog options

.TP
.B  \-\-pulsate
Set progress bar indeterminate
.TP
.B \-\-auto\-close
Close window when 100% has been reached


.SH EXAMPLES

Display file content and edit it : 
.IP
temp=$(mktemp)
cat "$N" | zeniTK --text-info --title "$1" > $temp
if [ -n "$(cat $temp)" ]; then
	mv $temp "$N"
fi
.PP
Show a progress bar. 
Percent and messages are shown via stdin. Percent is a simple number and message starts with a "#" : 

.PP
i=0
.PP
(while true; do 
.PP
	echo "# Progress : $i%"
.PP
	echo $i
.PP
	i=$(($i+1)) # increment i 
.PP
	sleep 0.1
.PP
done ) | zeniTK --progress

.PP Ask a question
.IP
zeniTK --question --text "Do you like pancakes?"

.PP --list usage
.IP
zeniTK --text "Choose your meal" --list "pancakes" "Big burger" "Onion soup"


.SH SEE ALSO
\fBzenity\fP(1)
.SH BUGS
Please report to thuban <thuban@yeuxdelibad.net>
