#!/bin/sh

DEVCLASS=${1}
DEVNAME=${2}
MOUNTROOT=/mnt

case "${DEVCLASS}" in
		0)
			if [ -n "$(echo $DEVNAME | grep -o "ugen[0-9]")" ]; then
				addr=$(usbdevs -d | \
					grep -B1 $DEVNAME | \
					grep -o [0-9]: |\
					grep -o [0-9])
				chown _cups /dev/${DEVNAME}.* /dev/usb$addr
			fi
		;;

        2)
		# disk devices
		# thanks to 
		# https://www.tumfatig.net/20110903/automount-usb-stick-on-openbsd/
		disklabel=`/sbin/disklabel $DEVNAME 2>&1 | sed -n '/^disk: /s/^disk: //p'`
		case $disklabel in
			"SCSI disk")
				slices=`/sbin/disklabel $DEVNAME 2>&1 | sed -n '/^ *[abd-z]: /s/^ *\([abd-z]\):.*/\1/p'`
				for slice in ${slices}; do
					mkdir -p -m 1777 $MOUNTROOT/$DEVNAME$slice
					mount /dev/$DEVNAME$slice $MOUNTROOT/$DEVNAME$slice
				done
			;;
		esac
        ;;
esac
