#!/bin/sh

DEVCLASS=$1
DEVNAME=$2

case $DEVCLASS in
        2)
                #/sbin/disklabel sd1 2>&1 | sed -n '/^label: /s/^label: //p'
                /sbin/umount "/mnt/$DEVNAME"
                rm -r "/mnt/$DEVNAME"
                exit 0
        ;;
esac
exit 0
