#!/bin/sh
#Script pour convertir des fichiers audios en ogg
# requiet vorbis-tools, sox, mpg321

#Dans Thunar, choisir Edition > Configurer les actions personnalisées >
# > Ajoutez une nouvelles entrée
# Nom : Convert2ogg
# Commande : /chemin/vers/le/script %F
# Conditions d'apparition : * 
# Cocher "Fichiers audio"
v_=$IFS
IFS='
'
for i in $@; do
	case $i in
		*.mp3 | *.MP3)
		mpg321 $i -w raw && oggenc raw -o ${i%.mp3}.ogg && rm raw
		;;
		*.wav )
			oggenc "$i" -o ${i%.wav}.ogg 
		;;
		*)
			j="${i%.*}"
			# on extrait le son
            #avconv -i "$1" -vn -ar 44100 -ac 2 -ab 256k "$j".wav
            sox $i $j.wav
			oggenc "$j.wav" -o "$j.ogg"
			rm $j.wav
		;;
	esac
			
done
IFS=v_
exit
