.Dd $Mdocdate$
.Dt isotop FAQ
.OS
.Sh NAME
.Nm isotop
.Nd a simple, fun (?) and pre-configured OpenBSD.

.Sh DESCRIPTION
.Nm 
is a script to configure OpenBSD into a great desktop.
As much as possible, tools included in base installation are used.
Therefore, some choice have been made to focus on simplicity and
efficiency.

.Sh FAQ
.Ss How to use this desktop?

The window manager is a slightly modified
.Lk http://dwm.suckless.org/ dwm
.

It is light, simple and help not to bother window arrangement.

Before trying another window manager or desktop environment, give dwm a
try. It is configured to be easier to use.

Quickstart : 

On the upper left, you can see tags numbers where you can assign
windows, followed by symbols showing layout. Clic on them to change the
displayed tag and the layout used.

On the upper right, you can see a status bar.

A few shortcuts

.Ss How can I configure WiFi ?
Read
.Xr hostname.if 5
and
.Lk https://www.openbsd.org/faq/faq6.html#Wireless FAQ-Wireless
A tool will be included in next version of isotop to ease this task.
.Ss How can I add/remove packages ?
A link to 
.Em pkg_mgr
is in cwm menu.

Else, read
.Lk https://www.openbsd.org/faq/faq15.html Package Management
https://www.openbsd.org/faq/faq15.html Package Management

.Ss Why can't I reboot or shutdown ?
You user must belong to wheel group to use cwm menu shortcuts.

.Ss Why is my screen red ?
Because we care about you eyes, 
.Xr sct 1
is started when you open a session.
Use dsch to change screen temperature color.
You can also disable this feature by removing sct line in 
.Pa $HOME/.xsession

.Ss What notification daemon can I use?
You can install 
.Em dunst
a
nd add in 
.Pa $HOME/.xsession
.Dl dunst &
.Ss Why cmus is the default music player ?
It is light, don't need huge dependencies. It is hackable, and even
usable with the mouse if you don't like keyboard. You cas of course
install any other music player you might prefer.
.Ss How to exit cmus without closing it ?
If you start cmus with cwm root menu, it is started in 
.Xr tmux 1
, so it can be detached or opened in
multiple terminals.
To detach, press "ctrl-b" then "d".
.Ss What are the differences with a vanilla OpenBSD ?
.Bl -bullet
.It 
.Xr unwind 8
is configured as default domain name resolver.
.It 
A script called zerohosts is used to adblock some domains by filling 
.Pa /etc/hosts

It will in include the content of
.Pa /etc/hosts.include

It updates
the "bad domains" list weekly and is called with 
.Pa
/etc/rc.local
No matter the DNS resolver you use, bad domains are blacklisted.
.It
Customized message in 
.Pa /etc/boot.conf
.It 
Enabled services : xenodm, unwind.
.It
Disable ulpt for USB printers. This happens in rc.shutdown to enjoy
KARL at reboot. 
See 
.Lk https://marc.info/?l=openbsd-misc&m=155746672110488&w=2 this thread
.It
ntpd configuration does'nt use google as a constraints
.It
Xenodm appearance is configured and configurable with a script called
xenodm-config.
.It 
Additional packages are installed
See 
.Pa /usr/local/share/isotop/data/packages
.It
doas is configured to avoid entering password for some commands. See
.Pa /etc/doas.conf
.It
.Xr cwm 5
is the default window manager. It is pre-configured and shipped
with various script to ease window management for non-keyboard users.
.It
iridium is the default browser. Are disabled every option related to
google and tracking. It is unveiled by default :
this means the browser can\(cqt read files on your computer except in
\(ti/Downloads. It keeps your ssh keys and passwords in configuration
files safes. 
Firefox is also making calls to google and can\(cqt be unveiled for now 
(see
.Lk https://marc.info/?l=openbsd-misc&m=152872551609819&w=2 this thread
)
.It
Alt-L is mapped as Esc for vi users :)
.It 
Translations are included : english and french for now.
.It 
A few scripts and tools are included in 
.Pa /usr/local/share/isotop/bin
and available in your 
.Ev PATH
.No .
See 
.Sx What scripts are shipped ?
.It
.Pa $HOME/.aliases 
and 
.Pa $HOME/.functions 
are filled with some (useful ?) stuff.
.It
$HOME/.kshrc contains some autocompletion for OpenBSD.
.It
A random wallpaper is set a each session.
.It
The file browser is pcmanfm. It is configured to have custom actions
accessible with a right click (edit image, upload a file...).
.It
The mouse pointer is hidden after a while using 
.Xr xbanish 1
.It
nord colorscheme for X apps is installed. See
.Lk  https://www.nordtheme.com/

.El

.Ss Why this name ?

At first, isotop was a iso file containing all packages and
configuration for intallation.
Now it\(cqs just a script to configure a vanilla OpenBSD.

Like an isotope it is a
variant of OpenBSD with a few more things inside, but still OpenBSD.

.Ss Why is it dark ?
Because the developper like it, and it saves power.

.Ss Can I install another web browser ?

Of course.
Firefox and chromium, amongst others, are available in ports.
However, we choosed iridium because it is unveiled, meaning it can\(cqt access your personal files that might
contains password or ssh keys and it is more privacy friendly than chromium.

.Ss Can I install another desktop environment ?
Of course.

Gnome, kde, lxde, xfce and more are availables for OpenBSD via ports.

.Ss What process are started when I open a session ?

See and edit
.Pa $HOME/.xsession

See 
.Lk https://tools.suckless.org/dmenu/ dmenu website

.Ss Where are isotop files stored ?

.Pa /usr/local/share/isotop

.Ss What scripts are included ?

.Bl -bullet
.It
dalarm : Specify an alert, then a number of minutes. A notification will
show the alert after the delay.
.It
dcmus : choose a file to play in cmus playlist
.It
dfm : a file launcher using dmenu.
.It
dgroupwin : select a window and assign a group
.It 
xclockstatusbar : display a bar with various info at the top of the
screen
.It
maxwin : maximize a window according to cwm's configuration and gap
.It 
dman : read a manpage
.It
dmenu_run_i : a dmenu_run improved to launch a command. End with a "!"
and the command is open in a terminal. Example : 
.Cm top!
.It
dsch : Search on the web.
Default search engine is duckduckgo if you do not specify a search
engine.

Examples : 

.D1 default engine : openbsd full disk encryption
.D1 search on openbsd misc list : obsdmisc firefox crash

.It
dsct : configure temperature color of the screen.
.It 
dyt : download the video with 
.Xr youtube-dl 1
\&.
Selected url is pasted by default.
.It
gdoas : open xterm to type doas password used for other scripts such as
xenodm-config.
.It
imgmod : modify an image using 
.Xr gm 1
Supported modification are.
.Bl -bullet
.It
convert to jpg
.It 
convert to png
.It
convert to gif
.It 
resize
.It
turn left or right
.El

.It
imgopti : optimize an image to reduce its size.
.It
networkcheck : check internet access
.It
openbsdupgrade : upgrade to last -stable changes with
.Xr syspatch 8
.Xr fw_update 1
.Xr pkg_add 1
.It
pixcol : show the html color code under the pointer 
.It
pixup : upload an image to pix.toile-libre.org
.It
rdmwall : set a random wallpaper. Backgrounds are searched in : 
.Pa $HOME/Images/Wallpapers
;
.Pa /usr/local/share/isotop/walls
.It
scrot : take a screenshot, saved in $HOME
.It
scrotup : take a screenshot with scrot and upload with pixup
.It
send_dmesg.sh : send your dmesg to OpenBSD developers to help hardware supporte.
.It
setwall : set desktop background.
.It
web : a wrapper to start a web browser.
.It
xenodm-config : edit xenodm configuration and appearance.
.El

.Ss What are avaiable custom actions in pcmanfm ?

.Bl -bullet
.It 
Modify image (turn, resize...)
.It
Optimize image
.It
Upload image
.It
Set as wallpaper
.It
Play in cmus
.It
Print with default printer (image, text, pdf...)
.El


.Sh How to use my desktop ?

.Ss Start an application

At first, the desktop is almost empty. 

There is xclock at the top left border.

Right-click on the background to see the application menu and select, by
example, xterm. 

You can also press Alt-p to show 
.Cm dmenu 
and type 
.Dq xterm
then press return.

Last, you can move the pointer to the bottom-left corner to pop 
jgmenu.

.Ss Basic window management

You can drag the window by pressing Alt and left-clicking on the window
to move it around. 

To resize the window, press Alt and right-click.

You probably don't need to move and resize windows but to see maximized
instead, or hide it. All of this can be done with keystrokes thanks to
.Xr cwm 1
but you might not remember them all the time. Some shortcuts are
avaiable in cwm's aplication menu.

.Ss Bindings

Keyboard and mouse bindings are 
.Xr cwm 1 
defaults. 

Some other are added : 

.Bl -bullet
.It
Alt-F4 : close window
.It
Alt-Shift-h/j/k/l : move window to the left/bottom/top/right of the
screen.
.It
Alt-s : start 
.Cm dsch 
.It
Alt-x : start
.Cm dfm 
.It
Alt-t and Alt-Shift-t : tile windows
.It
Alt-p : shown dmenu to start application
.It
Alt-f : show window menu
.It
Alt-g : assing a new group to focused window
.El

See
.Xr cwmrc 5
to customize according your needs.

.Ss Mouse bindings

You can popup menus by clicking on the desktop, on the clock or on the 
.Em 
border 
.No
of a
window (quite big by default).

.Bl -bullet
.It
Right click : Application menu. you can start an application or deal
with you windows.
.It
Middle click : group menu : show active group to toggle visibility of
groups.
.It
Left click : window menu, to select a window.
.It 
Scroll on the background to change volume.
.It 
Alt + Right click : resize window
.It 
Alt + Left click : drag window
.El


.Ss About window menu

The window menu looks like this : 

.Bd -literal
(4) ![] window name
(4)  [] other window name
(2) &[] another window name
(1) &[foo] again a window name
.Ed

Between parenthesis, the group assigned to the window.

.D1 ! means the window is focused.
.D1 & means the window is hidden.
.D1 [foo] : the window get the label "foo" with Ctrl-alt-n shortcut

.Ss About workspaces

There are no workspaces. They are just a way to increase the size of the
screen, and if you need a bigger screen, the window manager is probably
wrong somewhere.
Instead, cwm uses 
.Em groups
\(.
You can choose to show one ore more grouped windows depending on your
needs.

You can automatically assign a group to a window in 
.Pa $HOME/.cwmrc
or you can use the 
.Cm dgroupwin
to assing a group to a window.

At any time, a middle click on the desktop will show the group menu to
toggle the visibility of active groups.

.Sh About dmenu
Tools included use dmenu.

It is a menu printed at the top of your screen.
Write what you need, on only part of it, then press return to select.

.D1 Return: select
.D1 Esc: exit dmenu.
.D1 ctrl-y: paste selection




.Sh BUGS
Of course.

Please report them to 
.An prx 
.Mt prx@ybad.name

.Sh SEE ALSO

.Xr cwm 1
.Xr cwmrc 5
.Xr dmenu 1
.Xr tmux 1

