.Dd $Mdocdate$
.Dt isotop FAQ 7
.Os
.Sh NAME
.Nm isotop
.Nd customized OpenBSD for ease of use and fun.

.Sh DESCRIPTION
.Nm 
is made of two scripts :
.Bl
.It
isotop-user.sh : install a user session and a bunch of tools to make
it easy to use. No need to be root.
.It
isotop-root.sh : add ports and configure parts of the system that
require root privileges.
.El

Base tools if preffered, thus some choices have been made to keep a
system as simple and efficient as possible.

.Sh Read this later

Run "man isotop" to read this help later.

.Sh FAQ
.Ss How to use this desktop environment?
Isotop's default window manager is a slightly modified
.Lk http://dwm.suckless.org/ dwm
\&.

Before installing a new window manager, give dwm a try. It has been made
as simple as possible.

.Bd -literal -offset indent
 +------+----------------------------------+--------+
 | tags | title                            | status +
 +------+---------------------+------------+--------+
 |                            |                     |
 |                            |                     |
 |                            |                     |
 |                            |                     |
 |          master            |        stack        |
 |                            |                     |
 |                            |                     |
 |                            |                     |
 |                            |                     |
 +----------------------------+---------------------+
.Ed

On the upper left, you can see workspaces (tags) followed by window layout
symbol. There a 4 availables
:
.Bl -bullet
.It
tiled []=,
.It
monocle [1],
.It
floating ><>,
.It
deck DD
.El

You can click on it to change.

On the top, you can see the selected window title.

On the top right, you can see a status bar.

To understand how it works, open a terminal with Alt-Shift-Enter or
left-click on the status bar and select Firefox. You see the new window
on the right, in the stack. The first window stays in the master area.

Alt-j or Alt-k switch selected window.

Alt-n, where n is a number, display windows tagged "n".

Alt-Shift-n stick the tag n to the selected window.

Alt-Ctrl-n display other tagged windows.

Alt-Enter or middle-clic on the title bar push the window in
the master area.

right-click on the window title or Alt-Shift-c close the window.

Move a window with Alt-left-button.

See 
.Xr dwm-isotop 1
for more and of course
.Xr dwm 1

.Ss How to install isotop for another user ?
Use
.Cm isotop-user.sh
with this user.

See
.Sx What isotop-user.sh does ?
.Ss How to recompile dwm, dmenu, slstatus, lsdesktop, rover ?
They are in
.Pa isotop-files/src
unless you deleted this directory.

.Ss How to add a printer ?
Add a few ports:
.Bd -literal -offset indent
# pkg_add cups cups-filters cups-libs foomatic-db gutenprint\
gtk+2-cups gtk+3-cups gtk+4-cups
.Ed

Enable cups:
.Bd -literal -offset indent
# rcctl enable cupsd cups_browsed
# rcctl start cupsd cups_browsed
.Ed

and maybe read
.Sx How to use an USB printer ?

Open a browser to 
.Lk http://127.0.0.1:631
then click on 
"Administration"

.Ss How to use an USB printer ?
Add these lines in
.Pa /etc/rc.shutdown
.Bd -literal -offset indent
printf 'disable ulpt\nq\n' | config -ef /bsd
sha256 /bsd >/var/db/kernel.SHA256
.Ed

then reboot.

It disable ulpt to use an USB printer and rebuild kernel checksum.

Change permissions for cups.
Check which is your printer with
.Bd -literal -offset indent
# usbdevs -vd
.Ed

Then :
.Bd -literal -offset indent
chown _cups /dev/ugen0.* /dev/usb2
.Ed

You can add this to 
.Pa /etc/rc.local
to keep changes at each reboot.

See
.Lk https://marc.info/?l=openbsd-misc&m=155746672110488&w=2 this thread

.Ss How to add a new WiFi network?
read
.Xr hostname.if 5

and try 
.Xr wobsd 1
included in isotop

.Ss How to add new software ?

Read 
.Lk https://www.openbsd.org/faq/faq15.html official faq

.Ss How to deal with USB drive ?
See
.Xr dmount 1

.Ss Why the screen seems red ?
To take care of your eyes, 
.Xr sct 1
is started with your session.
Edit
.Pa $HOME/.start
if you want to change this.

.Ss Why mpd is the default music player ?
It is light and easy to use without a full GUI.
.Cm ncmpc
is installed as a CLI interface and
.Xr dmpc 1
let you choose a song to play.

By default, all music placed in 
.Pa $HOME/mpd
is played by mpd.

You can change this by editing 
.Pa $HOME/.mpdconf

See
.Bl -bullet
.It
.Xr dmpc 1
.It
.Xr mpc 1
.It
.Xr ncmpc 1
.El

.Ss Why Firefox ?
It is unveiled so you SSH keys and personal data is safe. On ly
.Pa $HOME/Downloads
and
.Pa /tmp
are readable by this browser.

.Ss Why this name ?

It's like OpenBSD, but with a bit more on it :)

.Ss Why is it dark ?
Because the dev like it. It's nice on his eyes and require less power.

.Ss Can I install another desktop environment ?
Why not ?
A lot are available in ports.

.Ss What process are started when I open a new session?
See
.Pa $HOME/.start

.Ss What scripts are included ?
See
.Pa $HOME/bin
and their manpages.

.Ss What does isotop-user.sh do?

It sets /home/user permission to 700

It installs a customized dwm window manager (see
.Xr dwm-isotop 1
), 
.Xr dmenu 1
with mouse support
.Xr slstatus 1
to display a nice status bar
.Xr lsdesktop 1
to start apps with a desktop file, 
.Xr rover 1
a file manager and latest version of
youtube-dl. See
Xr getytdl.

It also copies a few configuration files :

.Bl -bullet
.It
.Pa .Xresources
: colored using
.Lk  https://www.nordtheme.com/ nord theme
.It
.Pa .aliases, .functions
.Pa .bookmarks
: a list of url used with
.Xr dloadbmk 1
and
.Xr daddbmk
.It
.Pa .config
containing config for
.Xr dunst 1
,
.Xr xfe 1
,
.Xr mpv 1
, gtk3 appearance and ignored files with
.Xr lsdestop 1
.It
.Pa .dmenurc
a file to keeep appearance of 
.Xr dmenu 1
consistent
.It
.Pa .exrc
.Xr vi 1
configuration
.It 
.Pa .first.sh
a script started the first time you see your isotop session.
.It
.Pa .gtkrc-2.0
gtk appearance
.It
.Pa .kshrc
ksh configuration with autocompletion and nice prompt.
.It
.Pa .local/share/applications
: containing a few .desktop files for isotop scripts.
.It 
.Pa .mpdconf
: configuration file for
.Xr mpd 1
.It
.Pa .profile
: set environment variables such as BROWSER, PATH and MANPATH.
.It
.Pa .start
: commands started at the beginning of a session, called by
.Pa .xsession
.It
.Pa .wallpapers
: a directory with your favourite wallpapers picked randomly.
Use
.Xr dwall 1
To change it.
.El

A few tools are available in
.Pa bin

isotop's manpages are available in 
.Pa $HOME/man

.Ss What isotop-root.sh does ?

This script make some changes on the whole system. You are not forced to
use it, as it require root privileges. 

.Bl -bullet
.It
Configure
.Xr xenodm 1
appearance.
The wallpaper used is in 
.Pa /usr/local/share/isotop/walls/loginbg.jpg
.It
Enable softdeps
"softdep"
to speed up diksk
.It
Install a script
.Pa /etc/rc.local
started at each boot
to update block list for
.Xr unwind 8
.It
.Xr unwind 8
and
.Xr dhclient.conf 5
are configured to be a local domain name resolver.

A file
.Pa /var/unwind.block
is filled with a list of unwanted domains (ad-filter).

This list is gathered from 
.Lk https://ybad.name/evils.html
.It
.Xr apmd 8
is configured and enabled to save power
.It
.Xr doas 1
is configured to avoid the request of a password to mount drives or
reboot the machine. (facultative)
.It
ntpd doesn't use google as a constraint.
.It
A few ports are installed. See
.Lk https://framagit.org/3hg/isotop/-/blob/master/isotop-files/packages.txt
.It
/tmp is mounted in RAM using mfs. 10% of available memory is used.
.El

.Ss Why dwm?
Moving and resizing windows takes a lot of time. dwm tries to answer
this situation and let the user be really focused on this work instead
of managing windows.

When too much windows are open, we can hide them using "monocle" or
"deck" layout.

Finally, dwm is light and reliable. It is also pledged, see
.Xr pledge 2

.Sh About dmenu
A lot of isotop tools use dmenu. it is patched to enjoy mouse support.

Also see :
.Xr dmenu 1
and
.Lk https://tools.suckless.org/dmenu/ dmenu's website


.Sh BUGS
Of course
Please let me know :

.An prx
.Mt prx@ybad.name

.Sh SEE ALSO

.Lk https://www.openbsd.org/faq/index.html Official OpenBSD FAQ

.Lk https://framagit.org/3hg/isotop/ dépôt d'isotop

.Lk https://dwm.suckless.org/tutorial/ Tuto officiel dwm

.Lk https://ratfactor.com/dwm Tuto de Dave Gauer

.Xr dwm-isotop 1
.Xr dmenu 1
.Xr firefox 1
.Xr mpc 1
.Xr mpd 1
.Xr ncmpc 1
.Xr tmux 1
.Xr slstatus 1
.Xr dunst 1

.Xr bdmenu 1
.Xr checkbatt 1
.Xr daddbmk 1
.Xr dalarm 1
.Xr ddesktop 1
.Xr dfm 1
.Xr dloadbmk 1
.Xr dlocate 1
.Xr dman 1
.Xr dmount 1
.Xr dmpc 1
.Xr dsch 1
.Xr dsct 1
.Xr dsession 1
.Xr dshot 1
.Xr dsshmenu 1
.Xr dumount 1
.Xr dwall 1
.Xr dyt 1
.Xr gdoas 1
.Xr getytdl 1
.Xr imgmod 1
.Xr imgopti 1
.Xr lsdesktop 1
.Xr networkcheck 1
.Xr openbsdupgrade 1
.Xr pixup 1
.Xr rdmwall 1
.Xr rover-open 1
.Xr scratchterm 1
.Xr scrot 1
.Xr send_dmesg 1
.Xr setwall 1
.Xr term 1
.Xr wobsd 1
