#!/bin/sh

DIR=~/Documents/notes
mkdir -p $DIR

if [ $# -eq 0 ]; then # nothing to edit
	N=$DIR/$(zeniTK --title="Nouvelle note" --text="Nom de la nouvelle note : " --entry)
else
	N="$1"
fi

if [ -n "$N" ]; then
	temp=$(mktemp)
	cat "$N" | zeniTK --text-info --title "$1" > $temp
	if [ -n "$(cat $temp)" ]; then
		mv $temp "$N"
	fi
	rm $temp
fi
exit

