#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

xsetroot -solid "#345583" 
if [ -f ~/.fluxbox/lastwallpaper ]; then
	wpsetters=feh fbsetbg -l &
else
	wpsetters=feh fbsetbg -a ~/Images/Wallpapers/diodonBSD-peha.png &
fi
xset -display :0 s off -dpms &
numlockx &
redshift-gtk -l 47.13:1.33 -t 5500:4000 &
conky -c ~/.fluxbox/conky.conf &
tray-vol &

which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
