#!/bin/sh
# prx -- prx@ybad.name.
# Licence:  MIT
# 
# Create a list of domains to block with unwind 
# with option "block list file.txt"
# usage : unwind-block > file.txt

set -e

D="ftp -o-"

HOSTSSRC="
https://adaway.org/hosts.txt
https://someonewhocares.org/hosts/zero/hosts
https://hosts-file.net/ad_servers.txt
https://www.malwaredomainlist.com/hostslist/hosts.txt
http://winhelp2002.mvps.org/hosts.txt
"

DOMAINSSRC="
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=nohtml&showintro=1
https://mirror.cedia.org.ec/malwaredomains/justdomains
https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt
https://feodotracker.abuse.ch/blocklist/?download=domainblocklist
https://zeustracker.abuse.ch/blocklist.php?download=baddomains
"

(
	for URL in ${HOSTSSRC}; do
		${D} "${URL}" | \
		sed -e 's/#.*$//g' |\
		tr -s '[:blank:]' |\
		awk '{print $2}'
	done

	for URL in ${DOMAINSSRC}; do
		${D} "${URL}" 
	done
) | sort -u
exit 0
