.Dd $Mdocdate$
.Dt FAQ isotop
.OS
.Sh NAME
.Nm isotop
.Nd une OpenBSD préconfigurée, simple (et amusante ?)

.Sh DESCRIPTION
.Nm 
est un constitué de deux scripts permettant de configurer OpenBSD pour obtenir un environnement de
travail rapide, agréable et pratique.
Les outils présents de base dans OpenBSD sont
privilégiés. Par conséquent, certains choix ont été faits pour se
concentrer sur un système simple et efficace.

.Sh FAQ

.Ss Comment me servir de ce bureau ?
Le gestionnaire de fenêtres par défaut dans isotop est 
.Lk http://dwm.suckless.org/ dwm
avec quelques modifications.

Avant d'installer un autre gestionnaire de fenêtres ou environnement de
bureau, essayez dwm. Nous avons essayé de le rendre plus simple à
utiliser qu'il ne l'est déjà, et cela demandera peut-être un temps
d'adaptation.

Pour commencer : 

En haut à gauche, vous voyez les numéros des espaces de
travail (étiquettes données aux genêtres) suivi d'un symbole. Vous pouvez cliquer dessus pour en changer.

En haut à droit, une barre de status indique l'heure, la date, le
volume sonore, la charge de la batterie et la chanson jouée.

Quelques raccourcis : 

.Bl -bullet
.It 
clic gauche sur la barre de status ou le fond d'écran : affiche le menu pour
ouvrir une application
.It 
clic droit sur la barre de status ou le fond d'écran : affiche le menu de session
.It 
clic gauche ou scroll sur le titre d'une fenêtre : affiche la
fenêtre suivante.
.It 
clic droit sur le titre d'une fenêtre : ferme la
fenêtre.
.It 
ctrl-shift-Enter : ouvre un terminal
.It 
alt-p: affiche dmenu pour ouvrir une application
.El

Bien sûr, ce n'est qu'un mince aperçu.
Voir 
.Xr dwm-isotop 1
pour plus d'informations sur les possibilités de la session
isotop.

.Ss Comment installer isotop pour un autre utilisateur ?
Facile, il suffit de lancer le script d'installation 
.Sx Que fait isotop-user.sh ?
avec cet
utilisateur. Seule la configuration utilisateur sera copiée.

.Ss Comment recompiler dwm, dmenu, slstatus, lsdesktop, rover ?

Ces outils sont disponibles dans le dossier
.Pa isotop-files/src
disponibles après installation dans votre dossier personnel. Ils
sont toujours là si vous ne les avez pas supprimés. Sinon,
voir ici :

.Lk https://framagit.org/3hg/isotop/-/tree/master/isotop-files/src

.Ss Comment ajouter une imprimante ?
Installez les paquets suivants : 
.Bd -literal -offset indent
# pkg_add cups cups-filters cups-libs foomatic-db gutenprint\
gtk+2-cups gtk+3-cups gtk+4-cups
.Ed

Activez et démarrez cups:

.Bd -literal -offset indent
# rcctl enable cupsd cups_browsed
# rcctl start cupsd cups_browsed
.Ed

Si votre imprimante est reliée en USB, lisez
.Sx Comment utiliser une imprimante USB ?

Ouvrez un navigateur à l'adresse 

.Lk http://127.0.0.1:631

Puis cliquez sur l'onglet 
.Dq Administration

Voir aussi:

.Lk https://wiki.openbsd.fr.eu.org/doku.php/system/print/

.Ss Comment utiliser une imprimante USB ?
Ajoutez les lignes suivantes dans le fichier 
.Pa /etc/rc.shutdown

.Bd -literal -offset indent
printf 'disable ulpt\nq\n' | config -ef /bsd
sha256 /bsd >/var/db/kernel.SHA256
.Ed

Puis redémarrer.

Ceci a pour effet de désactiver ulpt pour les imprimantes USB.
et de reconstruire la somme de contrôle du noyau pour profiter de
KARL au redémarrage.

Une fois le redémarrage effectué, il faut donner les
permissions à cups de gérer cette imprimante.
Repérez-là avec la commande

.Bd -literal -offset indent
# usbdevs -vd
.Ed

Puis modifiez les permissions en conséquence selon le port sur
lequel l'imprimante est détectée : 

.Bd -literal -offset indent
chown _cups /dev/ugen0.* /dev/usb2
.Ed

Ajoutez la commande précedente au fichier 
.Pa /etc/rc.local
pour garder ces changements à chaque redémarrage.

Voir
.Lk https://marc.info/?l=openbsd-misc&m=155746672110488&w=2 ce fil

.Ss Comment configurer une connexion WiFi ?
Lisez le man
.Xr hostname.if 5
et la documentation d'OpenBSD traduite
.Lk https://wiki.obsd4a.net/openbsd.org:faq:faq6#reseau-sans-fil réseau sans fil
Un outil pour faciliter les connexions sera publié dans une prochaine
version d'isotop, lorsque le développeur aura une carte sans-fil.

.Ss Comment ajouter/supprimer des programmes
Ouvrez
.Xr pkg_mgr 1
dans un terminal.

Sinon, lisez
.Lk https://wiki.obsd4a.net/openbsd.org:faq:faq15 gestion des paquets.

.Ss Comment monter une clé USB ?
Voir
.Xr dmount 1

.Ss Pourquoi cups n'est pas installé par défaut ?
Tout le monde n'utilise pas une imprimante. Son installation est
laissée libre à chacun. Si vous en avez besoin lisez :
.Sx Comment ajouter une imprimante ?

.Ss Pourquoi mon écran semble rouge ?
Puisqu'on pense à vos yeux, on lance automatiquement en début de session
.Xr sct 1
Vous pouvez utiliser 
.Xr dsct 1
pour modifier la couleur, ou carrément retirer
.Cm sctd > /dev/null 2>&1 &
du fichier 
.Pa $HOME/.start
.

.Ss Pourquoi mpd est le lecteur de musique par défaut ?
Il est léger et ne nécessite pas de lourdes dépendances.
Par ailleurs, c'est très simple de le contrôler
grâce à divers scripts.
L'outil 
.Cm ncmpc
est installé pour vous donner une interface à mpd.
Par défaut, toute la musique placée dans le dossier
.Pa $HOME/Musique
sera disponible à la lecture.

À ce propos, voir : 

.Bl -bullet
.It
.Xr dmpc 1
.It
.Xr mpc 1
.It
.Xr ncmpc 1
.El

.Ss Quelles sont les différences avec une installation OpenBSD de base?
Voir
.Sx Que fait isotop-user.sh ?
et
.Ss Que fait isotop-root.sh ?

.Ss Pourquoi firefox est le navigateur par défaut.
Il est "unveiled" par défaut:
cela signifie que le navigateur ne peut lire des fichiers sur votre
ordinateur sauf dans
.Pa $HOME/Downloads
et
.Pa /tmp
pour plus de sécurité.

Il garde vos clés SSH et mots de passe inaccessibles par un éventuel
pirate.

Vous pouvez bien entendu en installer un autre si vous
préférez.



.Ss Pourquoi ce nom?

Au début, isotop était image iso contenant tous les paquetages et
configuration pour l'installation.
Maintenant, c'est juste un script pour configurer OpenBSD.

Comme un isotope c'est une
variante d'OpenBSD avec quelques éléments supplémentaires, mais toujours OpenBSD.

.Ss Pourquoi c'est sombre ?
Parce que le développeur aime bien, et ça économise l'énergie de ne pas
allumer les pixels.

.Ss Puis-je installer un autre environnement de bureau?
Bien sûr.

Gnome, kde, lxde, xfce et d'autres sont disponibles pour OpenBSD via les ports.

.Ss Quels processus sont démarrés lorsque j'ouvre une session?

Consultez le fichier
.Pa $HOME/.start

.Ss Quels scripts sont inclus?
Voir le contenu du dossier
.Pa $HOME/bin
Référez-vous au pages man correspondantes pour plus
d'information.

.Ss Que fait isotop-user.sh ?

Ce script installe le gestionnaire de fenêtre dwm (voir
.Xr dwm-isotop 1
) personnalisé, une version de 
.Xr dmenu 1
avec support de la souris, 
.Xr slstatus 1
pour afficher des informations dans la barre de status et
.Xr lsdesktop 1
permettant l'affichage des applications installées pour un menu.
.Xr rover 1
un gestionnaire de fichiers en mode texte.

De plus, il copie plusieurs fichiers de configuration : 

.Bl -bullet
.It
.Pa .Xresources
: configure la couleur des applications X (xclock, xterm...) avec le
thème 
.Dq nord
Voir
.Lk  https://www.nordtheme.com/
.It
.Pa .aliases, .functions
: Ajoute 
quelques commandes pratiques (ll, .., clbin, mktgz, mkcd, ...). Consultez le contenu
de ces fichiers pour en savoir plus.
.It
.Pa .bookmarks
: un fichier contenant des marques pages que vous pouvez charger avec 
.Xr dloadbmk 1
et compléter avec
.Xr daddbmk
.It
.Pa .config
contient la configuration pour
.Xr dunst 1
,
.Xr xfe 1
,
.Xr mpv 1
, l'apparence des applications gtk3 et une liste des entrées à
ignorer avec
.Xr lsdestop 1
.It
.Pa .dmenurc
un fichier permettant de modifier l'apparence de 
.Xr dmenu 1
de façon commune à plusieurs scripts
.It
.Pa .exrc
Fichier de configuration de 
.Xr vi 1
.It 
.Pa .first.sh
est un script qui est lancé à la première ouvrture
de session et affiche cette page de manuel
.It
.Pa .gtkrc-2.0
définit l'apparence des applications gtk
.It
.Pa .kshrc
Fichier de configuration du shell par défaut ksh. Ce dernier
permet d'afficher le dossier courant, une couleur spécifique si
une commande a échoué et quelques autocomplétions
pour des commandes relatives à OpenBSD.
.It
.Pa .local/share/applications
: Ce dossier contient plusieurs fichiers
.Dq .desktop
permettant de donner accès aux scripts intégrés
dans isotop
.It 
.Pa .mpdconf
: fichier de configuration pour
.Xr mpd 1
.It
.Pa .profile
: Fichier permettant de définir plusieurs variables
d'environnement telles que BROWSER pour définir le navigateur par
défaut ou encore la langue à utiliser, les dossiers où
se trouvent les binaîtres PATH et le dossier où se
trouvent les pages man supplémentaires MANPATH.
.It
.Pa .start
: Fichier permettant d'exécuter des commandes au démarrage
de la session. Il est lancé par 
.Pa .xsession
.It
.Pa .wallpaper
: Ce fichier est en fait une image qui sert de fond d'écran. Vous
pouvez la remplacer par ce qui vous plaît.
.El

Enfin, plusieurs outils sont disponibles dans le dossier
.Pa bin
Référez-vous au pages man correspondantes pour plus
d'information.

Enfin, le script installe les pages man livrées avec isotop dans
le dossier
.Pa $HOME/.isotop/man
et crée les dossiers habituellement utilisés par les
applications.


Ce script s'occupe de configurer plusieurs outils au niveau du
système tout entier. L'utilisateur est libre de l'utiliser ou
non.

.Bl -bullet
.It
Configuration de l'apparence de 
.Xr xenodm 1
Un fond d'écran est installé dans
.Pa /usr/local/share/isotop/walls/loginbg.jpg
.It
Activation des 
.Dq softdep
pour accélérer la lecture sur les disques
.It
Installation d'un fichier appelé par
.Pa /etc/rc.local
qui permet de mettre à jour la liste des domaines
blacklistés par
.Xr unwind 8
.It
Configuration d'
.Xr unwind 8
et
.Xr dhclient.conf 5
pour avoir un résolveur de nom local qui filtre aussi les pubs et
domaines malveillants.
est configuré en tant que résolveur de nom de domaine local
par défaut. Ainsi, vous ne dépendez pas d'un fournisseur
d'accès à internet pour réaliser cette tâche
(anti-censure).
.Pp
Un fichier
.Pa /var/unwind.block
contient une liste de domaines connus comme malveillants ou
publicitaires. Cette liste est mise à jour
une fois par semaine au démarrage via le script
.Pa /etc/rc.local.
.Pp
Cette liste est récupérée depuis le site
.Lk https://ybad.name/evils.html de l'auteur d'isotop.
Si vous essayez d’accéder à l’un de ces domaines (pourquoi?), Vous
obtiendrez un
message:
.Dq Le site web n'est pas disponible
.It
Configuration de la gestion d'énergie avec
.Xr apmd 8
.It
Configuration de 
.Xr doas 1
pour faciliter l'utilisation des outils isotop
.It
La configuration ntpd n'utilise pas google comme contrainte.
.It
Quelques programmes supplémentaires sont installés.
Voir
.Lk https://framagit.org/3hg/isotop/-/blob/master/isotop-files/packages.txt
.El

.Ss Pourquoi avoir choisi dwm?
Gérer les fenêtres occupe énormément de
temps. ON les déplace, on les redimensionne, pour souvent devoir
recommencer la minute suivante, en laissant plein de place
inutilisée à l'écran.

dwm propose une réponse à ce problème en arrangeant
automatiquement les fenêtres.

Lorsque trop de fenêtres sont ouvertes, il est rare de toutes les
afficher en même temps : dwm permet de passer en un mode
"maximisé" pour afficher une fenêtre en grand.

Enfin, dwm est un gestionnaire de fenêtres très
léger et rapide. Il est écrit en très peu de lignes
de code, profite du support de
.Xr pledge 2
ce qui le rend plus fiable et sûr.

Cependant, si vous en préférez un autre, n'hésitez
pas :)

.Sh À propos de dmenu
Les outils inclus utilisent dmenu patché pour pouvoir aussi
l'utiliser avec la souris.

C'est un menu affiché en haut de votre écran.
Écrivez ce dont vous avez besoin, ou une partie seulement, puis appuyez
sur Entrée pour sélectionner ou bien cliquez dessus
la lignee désirée. Un clic droit ou bien la touche echap
ferment le menu.

.Bd -literal -offset indent
Retour ou clic gauche: sélectionner
Esc ou clic droit: quitter le menu.
ctrl-y: coller la sélection
.Ed

Voir
.Lk https://tools.suckless.org/dmenu/ le site web de dmenu


.Sh BUGS
Bien sûr.

Veuillez les signaler à
.An prx
.Mt prx@ybad.name

.Sh SEE ALSO

.Lk https://framagit.org/3hg/isotop/

.Xr bdmenu 1
.Xr daddbmk 1
.Xr dalarm 1
.Xr dfm 1
.Xr ddesktop 1
.Xr dwm-isotop 1
.Xr dmenu 1
.Xr dmpc 1
.Xr firefox 1
.Xr mpc 1
.Xr mpd 1
.Xr ncmpc 1
.Xr pkg_mgr 1
.Xr tmux 1
.Xr slstatus 1
.Xr lsdesktop 1
.Xr dloadbmk 1
.Xr dunst 1
