#!/bin/sh
# $OpenBSD: Xsetup_0,v 1.3 2017/09/05 17:48:07 deraadt Exp $
WALLDIR=/usr/local/share/isotop/walls
if [ -f "${WALLDIR}"/loginbg.jpg ]; then
	WALL="${WALLDIR}/loginbg.jpg"
else
	WALL=$(find "$WALLDIR" | /usr/bin/sort -R | /usr/bin/head -n 1)
fi
/usr/local/share/isotop/bin/setwall "${WALL}" &

/usr/X11R6/bin/xclock -d -brief -render &
echo $! > /var/run/xclock.pid

